env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug" # for simplecov
language: ruby
before_install: bundle -v | grep -Fx "Bundler version 1.7.9" || gem install bundler --version 1.7.9
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
sudo: false
